import express from "express";
import assignment2Router from "../Assignment-2/app";
import assignment3Router from "../Assignment-3/app";
import assignment4router from "../Assignment-4/app";
import assignment5router from "../Assignment-5/app";
import assignment7router from "../Assignment-7/app";
import assignment9router from "../Assignment-9/app";
import assignment10router from "../Assignment-10/app";
import assignment11router from "../Assignment-11/app";
const router = express.Router();

router.use("/assignment-2", assignment2Router);
router.use("/assignment-3", assignment3Router);
router.use("/assignment-4", assignment4router);
router.use("/assignment-5", assignment5router);
router.use("/assignment-7", assignment7router);
router.use("/assignment-9",assignment9router);
router.use("/assignment-10",assignment10router);
router.use("/assignment-11",assignment11router);
export default router;
